<h1>Numpy Python</h1>
<h2>Numpy is used for numerical calculatons in data science</h2>
<a href='https://numpy.org/doc/stable/'>Documentation</a>
<ul>
    <li>A</li>
    <li>B</li>
    <li>C</li>
    <li>D</li>
</ul>

<ol>
    <li>A</li>
    <li>B</li>
    <li>C</li>
    <li>D</li>
</ol>

# Numpy
## subheading
**hello**
![alt text](https://numpy.org/doc/stable/_static/numpylogo.svg)

In [1]:
import numpy as np

In [3]:
mylist = [6,9,8,4,3,6,3,2,10]
my_arr = np.array(mylist, dtype = np.int8)

# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

In [4]:
my_arr

array([ 6,  9,  8,  4,  3,  6,  3,  2, 10], dtype=int8)

In [5]:
list2 = [[2,5,7],
         [7,8,0],
         [10,4,8]]
my_arr2 = np.array(list2)

In [7]:
my_arr2[1, 1]

np.int64(8)

In [8]:
my_arr2.item(1,1)

8

In [16]:
my_arr2.shape

(3, 3)

In [17]:
my_arr2.size

9

In [14]:
np.arange(1, 100, step =2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [23]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
ones = np.ones((3,3))

In [35]:
np.random.randint(100,size = (3,3))

array([[54, 42, 15],
       [98, 56, 38],
       [96, 72,  1]], dtype=int32)

In [36]:
np.random.rand(3,3)

array([[0.44155934, 0.67405421, 0.12418296],
       [0.67618225, 0.2112254 , 0.81017867],
       [0.69716255, 0.01659823, 0.29287016]])

In [7]:
np.random.choice([3,6,7,9],size=100)

array([3, 9, 9, 6, 7, 7, 9, 9, 3, 7, 6, 6, 3, 7, 9, 6, 9, 9, 6, 9, 3, 3,
       7, 7, 9, 6, 9, 7, 7, 9, 7, 7, 7, 6, 6, 9, 9, 7, 7, 9, 7, 9, 7, 6,
       3, 9, 3, 3, 9, 6, 7, 3, 3, 7, 9, 9, 6, 7, 6, 7, 7, 7, 6, 6, 6, 9,
       9, 7, 9, 7, 9, 9, 3, 3, 3, 9, 9, 7, 7, 3, 6, 9, 6, 7, 9, 7, 9, 7,
       7, 7, 3, 6, 3, 9, 3, 6, 9, 6, 3, 7])

In [44]:
list2 = [[4,6,7],
         [7,8,6],
         [4,4,8]]
my_arr3 = np.array(list2)

In [46]:
np.unique(my_arr3, return_counts=True, return_index=True)

(array([4, 6, 7, 8]), array([0, 1, 2, 4]), array([3, 2, 2, 2]))

In [47]:
my_arr3

array([[4, 6, 7],
       [7, 8, 6],
       [4, 4, 8]])

In [93]:
my_arr3[:  ,   -1:-3:-1]

array([[7, 6],
       [6, 8],
       [8, 4]])

In [102]:
my_arr4 = np.array([2,4,6,7,8,9,10,13,14])
my_arr4

array([ 2,  4,  6,  7,  8,  9, 10, 13, 14])

In [104]:
my_arr4[(my_arr4%2 != 0) | (my_arr4 >= 10)]

array([ 7,  9, 10, 13, 14])

In [53]:
arr_4 = np.random.randint(100,size = 12)

In [54]:
arr_4.shape

(12,)

In [41]:
arr_4.reshape(2,2,3)

array([[[54, 62, 29],
        [ 0, 35, 98]],

       [[ 8, 83, 93],
        [42, 91, 42]]], dtype=int32)

In [55]:
arr_4.resize((3,5))

In [56]:
arr_4

array([[29, 43, 72, 61, 84],
       [95, 59, 14, 17, 23],
       [46, 69,  0,  0,  0]], dtype=int32)

In [57]:
arr_4.flatten(order='F')

array([29, 95, 46, 43, 59, 69, 72, 14,  0, 61, 17,  0, 84, 23,  0],
      dtype=int32)

In [58]:
arr_4.transpose(1,0)

array([[29, 95, 46],
       [43, 59, 69],
       [72, 14,  0],
       [61, 17,  0],
       [84, 23,  0]], dtype=int32)

In [59]:
arr_4.swapaxes(1,0)

array([[29, 95, 46],
       [43, 59, 69],
       [72, 14,  0],
       [61, 17,  0],
       [84, 23,  0]], dtype=int32)

In [60]:
arr_4

array([[29, 43, 72, 61, 84],
       [95, 59, 14, 17, 23],
       [46, 69,  0,  0,  0]], dtype=int32)

In [65]:
arr_4.sort(axis=0)

In [66]:
arr_4

array([[ 0,  0,  0, 29, 43],
       [14, 17, 23, 46, 59],
       [61, 69, 72, 84, 95]], dtype=int32)

In [67]:
ss_arr_1 = np.random.randint(10, size=(2, 2))
print("ss_arr_1\n", ss_arr_1)
ss_arr_2 = np.random.randint(10, size=(2, 2))
print("ss_arr_2\n", ss_arr_2)

ss_arr_1
 [[9 0]
 [5 8]]
ss_arr_2
 [[7 5]
 [1 2]]


In [69]:
np.vstack((ss_arr_1,ss_arr_2))

array([[9, 0],
       [5, 8],
       [7, 5],
       [1, 2]], dtype=int32)

In [70]:
np.hstack((ss_arr_1,ss_arr_2))

array([[9, 0, 7, 5],
       [5, 8, 1, 2]], dtype=int32)

In [73]:
np.delete(ss_arr_1,0,axis=0)

array([[5, 8]], dtype=int32)

In [74]:
ss_arr_3 = np.random.randint(10, size=(4, 4))
ss_arr_3

array([[6, 7, 9, 2],
       [3, 2, 1, 9],
       [1, 0, 5, 1],
       [7, 2, 7, 8]], dtype=int32)

In [76]:
np.split(ss_arr_3,2, axis= 1)

[array([[6, 7],
        [3, 2],
        [1, 0],
        [7, 2]], dtype=int32),
 array([[9, 2],
        [1, 9],
        [5, 1],
        [7, 8]], dtype=int32)]

In [77]:
arr_5 = ss_arr_3

In [78]:
ss_arr_3.resize(2,8)

In [80]:
arr_5.resize(4,4)

In [82]:
ss_arr_3

array([[6, 7, 9, 2],
       [3, 2, 1, 9],
       [1, 0, 5, 1],
       [7, 2, 7, 8]], dtype=int32)

In [83]:
arr_6 = ss_arr_3.copy()

In [85]:
arr_6.resize(2,8)

In [86]:
ss_arr_3

array([[6, 7, 9, 2],
       [3, 2, 1, 9],
       [1, 0, 5, 1],
       [7, 2, 7, 8]], dtype=int32)

In [89]:
print("ss_arr_1\n", ss_arr_1)
print("ss_arr_2\n", ss_arr_2)

ss_arr_1
 [[9 0]
 [5 8]]
ss_arr_2
 [[7 5]
 [1 2]]


In [90]:
ss_arr_1 + ss_arr_2

array([[16,  5],
       [ 6, 10]], dtype=int32)

In [93]:
ss_arr_1 % 2

array([[1, 0],
       [1, 0]], dtype=int32)

In [94]:
np.sum(ss_arr_2)

np.int64(15)

In [95]:
marks = np.array([[40,50,80,90],
                 [40,55,89,70],
                 [30,60,80,60]])

In [100]:
total_marks = np.sum(marks,axis=1)

In [101]:
total_marks

array([260, 254, 230])

In [125]:
arr_7 = np.random.randint(10,size = 10)

In [103]:
arr_7

array([4, 5, 5, 0, 5, 0, 6, 2, 7, 4], dtype=int32)

In [105]:
arr_7.sum()

np.int64(38)

In [106]:
arr_7.cumsum()

array([ 4,  9, 14, 14, 19, 19, 25, 27, 34, 38])

In [107]:
arr_7.prod()

np.int64(0)

In [108]:
arr_7.cumprod()

array([  4,  20, 100,   0,   0,   0,   0,   0,   0,   0])

In [109]:
arr_7.min()

np.int32(0)

In [110]:
arr_7.max()

np.int32(7)

In [111]:
arr_7.argmin()

np.int64(3)

np.int64(8)

In [114]:
arr_6.resize(4,4)

In [115]:
arr_6

array([[6, 7, 9, 2],
       [3, 2, 1, 9],
       [1, 0, 5, 1],
       [7, 2, 7, 8]], dtype=int32)

In [119]:
arr_6.min(axis=0)

array([1, 0, 1, 1], dtype=int32)

In [120]:
arr_6.argmin(axis=1)

array([3, 2, 1, 1])

In [122]:
arr_7.sort()

In [128]:
arr_7.argsort()
        0 1  2  3  4  5  6  7  8  9

array([0, 1, 3, 6, 5, 2, 7, 4, 8, 9])

In [146]:
marks = np.array([[40,50,80,90],
                 [40,55,89,70],
                 [30,60,80,60],
                 [40,50,80,90],
                 [40,55,89,70],
                 [30,60,80,60]])
total_marks = marks.sum(axis=1)
per = (total_marks/400)*100
ranking = per.argsort()[::-1]

for rank, index in enumerate(ranking):
    print("student no:",index+1)
    print("rank no:",rank+1)
    print("total marks:",total_marks[index])
    print("percentage:",per[index])
    print("*"*20)



student no: 1
rank no: 1
total marks: 260
percentage: 65.0
********************
student no: 4
rank no: 2
total marks: 260
percentage: 65.0
********************
student no: 2
rank no: 3
total marks: 254
percentage: 63.5
********************
student no: 5
rank no: 4
total marks: 254
percentage: 63.5
********************
student no: 6
rank no: 5
total marks: 230
percentage: 57.49999999999999
********************
student no: 3
rank no: 6
total marks: 230
percentage: 57.49999999999999
********************
